#!/bin/sh
CLASSPATH=src/clj:test:test-classes:classes/:script/jline-0.9.94.jar:../clojure-contrib/target/clojure-contrib-1.2.0-SNAPSHOT.jar

java $@ -XX:MaxPermSize=64m -cp $CLASSPATH jline.ConsoleRunner clojure.main -i src/clj/example/timer.clj
